### ISSUE TITLE
Where is the ODataService?

### ISSUE THREAD

**Issue by canberranet** [Sitefinity-SDK/travelling-agency#5]
Where is the ODataService?

The type 'Telerik.Sitefinity.Services.OData.ODataService', provided as the Service attribute value in the ServiceHost directive, or provided in the configuration element system.serviceModel/serviceHostingEnvironment/serviceActivations could not be found.

**Comment by grumpycatsaysno** [comment]
Hello,
The travelling-agency sample is not using ODataService. Could you please be more specific where did you found the attribute value 'Telerik.Sitefinity.Services.OData.ODataService'.
